# Generated by Django 5.1.7 on 2025-04-10 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='static/img/produto/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='static/img/produto/')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='static/img/produto/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(default='000.000.000-00', max_length=14)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('nome', models.CharField(default='Nome Desconhecido', max_length=100)),
                ('sobrenome', models.CharField(default='Sobrenome', max_length=100)),
                ('email', models.CharField(default='email@exemplo.com', max_length=50)),
                ('telefone', models.CharField(default='(00)00000-0000', max_length=15)),
                ('numero_casa', models.CharField(default='S/N', max_length=50)),
                ('cep', models.CharField(default='00000-000', max_length=9)),
                ('rua', models.CharField(default='Rua Desconhecida', max_length=50)),
                ('cidade', models.CharField(default='Cidade Desconhecida', max_length=50)),
                ('estado', models.CharField(default='Estado', max_length=20)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
