# Generated by Django 5.1.7 on 2025-03-29 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_produtoedit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='marca',
            new_name='descricao',
        ),
    ]
