# Generated by Django 5.1.7 on 2025-03-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_rename_marca_produto_descricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='produtoEdit',
        ),
    ]
