# Generated by Django 5.1.7 on 2025-03-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_delete_produtoedit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='imagem1',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/produto/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/produto/'),
        ),
    ]
