# Generated by Django 5.1.6 on 2025-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_rename_imagem_produto_imagem1_produto_imagem2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='email@exemplo.com', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='Estado', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_casa',
            field=models.CharField(default='S/N', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(default='Rua Desconhecida', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='Cidade Desconhecida', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='Nome Desconhecido', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
