# Generated by Django 5.1.6 on 2025-04-09 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_remove_cliente_endereco_cliente_cep_cliente_cpf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero_casa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome Desconhecido', max_length=100)),
                ('sobrenome', models.CharField(default='Sobrenome', max_length=100)),
                ('email', models.CharField(default='email@exemplo.com', max_length=50)),
                ('telefone', models.CharField(default='(00)00000-0000', max_length=15)),
                ('numero_casa', models.CharField(default='S/N', max_length=50)),
                ('cep', models.CharField(default='00000-000', max_length=9)),
                ('rua', models.CharField(default='Rua Desconhecida', max_length=50)),
                ('cidade', models.CharField(default='Cidade Desconhecida', max_length=50)),
                ('estado', models.CharField(default='Estado', max_length=20)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
